spring:
  datasource:
    url: jdbc:h2:mem:takehome
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


# AI配置
ai:
  mock:
    enabled: true # 默认为true，启用Mock模式
  api:
    key: "" # 留空则强制使用Mock，填写真实Key后可切换到真实AI